# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: AdventureGeoPlanner-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: AdventureGeoPlanner
      POSTGRES_USER: kodilla_user
      POSTGRES_PASSWORD: kodilla_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tripplanner-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tripplanner-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/AdventureGeoPlanner
      - SPRING_DATASOURCE_USERNAME=kodilla_user
      - SPRING_DATASOURCE_PASSWORD=kodilla_password
      - SPRING_PROFILES_ACTIVE=docker
      - SPOTIFY_CLIENT_ID=1c7be3850109498f953b58e9cde315bc
      - SPOTIFY_CLIENT_SECRET=d9a786a96ea44f9bbfa5228457b11589
    networks:
      - tripplanner-network

volumes:
  postgres_data:

networks:
  tripplanner-network:
