debug: true

server:
  port: 8080

jwt:
  secret: superTajnyKluczJWT12345678901234567890

spring:
  application:
    name: tripplanner-backend

  datasource:
    url: jdbc:postgresql://postgres:5432/AdventureGeoPlanner
    username: GeoPlanner
    password: AdventurePlan

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      indent_output: true

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: d9a786a96ea44f9bbfa5228457b11589
            client-secret: 1c7be3850109498f953b58e9cde315bc
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spotify
            scope: user-read-email, playlist-read-private
            client-name: Spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.milosz: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spotify:
  client-id: d9a786a96ea44f9bbfa5228457b11589
  client-secret: 1c7be3850109498f953b58e9cde315bc

nominatim:
  base-url: https://nominatim.openstreetmap.org
  user-agent: trip-planer/1.0 (admin@mydomain.com)
